version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.17 # Version LTS recommandée pour Next.js
    steps:
      - checkout
      
      # Restauration du cache
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/.npm
          
      # Build Next.js
      - run:
          name: Build Next.js
          command: npm run build
          
      # Tests
      - run:
          name: Run Tests
          command: npm run test:ci # Utilisation du script test:ci défini dans package.json
          
      # Stockage des résultats
      - store_test_results:
          path: ./coverage
          
      - store_artifacts:
          path: ./coverage
          destination: coverage-report

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test